### ISSUE TITLE
JOSS review: example scripts - additional dependencies?

### ISSUE THREAD

**Issue by AlexanderFabisch** [NVlabs/scene_synthesizer#3]
When running the example scripts on my computer (after pip install with `[all]`), I get the following errors:

```
$ python examples/stable_poses.py 
ValueError: string is not a file: /home/clemens/code/scene_synthesizer/tests/data/assets/shapenetsem_watertight/Mug/b46a9c35587a38f6e87dab59b7e63362.obj

$ python examples/isaaclab_kitchen_env_cfg.py
NameError: name 'configclass' is not defined

$ python examples/add_random_mdl_materials.py 
ModuleNotFoundError: No module named 'xatlas'
```

I guess there are some dependencies missing? (+ hardcoded path)

https://github.com/openjournals/joss-reviews/issues/7561

**Comment by clemense** [comment]
Thanks!

In the latest update (https://github.com/NVlabs/scene_synthesizer/commit/c292bf839d9366ac87c9af4682fb87c23c921582) I addressed all three issues:

* I removed the hardcoded path from `examples/stable_poses.py`
* I removed the file `example/isaaclab_kitchen_env_cfg.py` since it's not a self-contained runnable example, it was only used as a `literalinclude` in https://scene-synthesizer.github.io/examples/isaaclab_rl.html. I instead added it to the `rst` file directly.
* I added the missing dependency to the `setup.cfg`
